import './globals.css'
import { Lato } from 'next/font/google' //Importando fonte. Nessa nova versão do Next.js já vem as bibliotecas para usar as fontes do Google
import Header from "@/components/Header"

const lato = Lato({
  subsets: ['latin'],
  weight: ['400', '700'] //tem que passar quais grossuras das fontes você vai usar.
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={lato.className}>
        <Header />
        {children}
      </body>
    </html>
  )
}
